---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  client_rb:
   chef_license: accept
   product_name: chef
   product_version: 15
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: windows-2012r2

suites:
  - name: default
    run_list:
      - recipe[workstation::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
